# Generated by Django 2.2.3 on 2019-08-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='row_id',
            field=models.BigIntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='id',
            field=models.BigIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='projectuser',
            constraint=models.UniqueConstraint(fields=('id', 'project'), name='user identifier'),
        ),
    ]
