# Generated by Django 2.2.3 on 2019-08-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190809_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='row_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
