# Generated by Django 2.2.3 on 2019-07-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='@website', max_length=30)),
                ('default', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=30)),
                ('access', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LanguageField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField()),
                ('owner_id', models.BigIntegerField()),
                ('state_id', models.BigIntegerField()),
                ('host', models.CharField(default='@website', max_length=30)),
                ('language', models.CharField(max_length=2)),
                ('field', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=1000000000)),
            ],
        ),
    ]
